package com.bhashasetu.service;
import static org.assertj.core.api.Assertions.assertThat; import com.bhashasetu.model.*; import com.bhashasetu.repository.SchemeRepository; import java.util.*; import org.junit.jupiter.api.*; import org.mockito.Mockito;
class EligibilityServiceTest {
 private final NormalizationService normalizer=new NormalizationService(); private final SchemeRepository repo=Mockito.mock(SchemeRepository.class); private final EligibilityService service=new EligibilityService(repo,normalizer);
 private Scheme scheme(Object value){Scheme s=new Scheme();s.setName("Student scholarship");s.setActive(true);EligibilityRule r=new EligibilityRule();r.setScheme(s);r.setField("age");r.setOperator("<=");r.setValue(value);r.setValueType("integer");s.getRules().add(r);return s;}
 @Test void structured_match_is_eligible(){Scheme s=scheme(18);Mockito.when(repo.findByActiveTrueOrderByNameAsc()).thenReturn(List.of(s));var result=service.evaluateAll(Map.of("age",17)).get(0);assertThat(result.status()).isEqualTo("ELIGIBLE");}
 @Test void manual_conditions_make_potential_without_changing_rule_outcome(){Scheme s=scheme(18);s.setManualConditions(List.of("Domicile proof must be checked."));Mockito.when(repo.findByActiveTrueOrderByNameAsc()).thenReturn(List.of(s));assertThat(service.evaluateAll(Map.of("age",17)).get(0).status()).isEqualTo("POTENTIALLY_ELIGIBLE");}
 @Test void missing_fact_needs_information(){Scheme s=scheme(18);Mockito.when(repo.findByActiveTrueOrderByNameAsc()).thenReturn(List.of(s));assertThat(service.evaluateAll(Map.of()).get(0).status()).isEqualTo("NEED_MORE_INFORMATION");}
 @Test void known_failure_overrides_manual_conditions(){Scheme s=scheme(18);s.setManualConditions(List.of("Manual proof"));Mockito.when(repo.findByActiveTrueOrderByNameAsc()).thenReturn(List.of(s));var result=service.evaluateAll(Map.of("age",19)).get(0);assertThat(result.status()).isEqualTo("NOT_ELIGIBLE");assertThat(result.manualConditions()).contains("Manual proof");}
 @Test void state_aliases_match_rules(){Scheme s=rule("state_or_ut","==","Uttar Pradesh");Mockito.when(repo.findByActiveTrueOrderByNameAsc()).thenReturn(List.of(s));assertThat(service.evaluateAll(Map.of("state_or_ut","UP")).get(0).status()).isEqualTo("ELIGIBLE");s=rule("state_or_ut","==","Odisha");Mockito.when(repo.findByActiveTrueOrderByNameAsc()).thenReturn(List.of(s));assertThat(service.evaluateAll(Map.of("state_or_ut","Orissa")).get(0).status()).isEqualTo("ELIGIBLE");}
 @Test void category_alias_matches_rule(){Scheme s=rule("social_category","==","SC");Mockito.when(repo.findByActiveTrueOrderByNameAsc()).thenReturn(List.of(s));assertThat(service.evaluateAll(Map.of("social_category","Scheduled Caste")).get(0).status()).isEqualTo("ELIGIBLE");}
 @Test void broad_and_narrow_occupation_is_missing_not_rejected(){Scheme s=rule("occupation","==","Small and marginal farmer");Mockito.when(repo.findByActiveTrueOrderByNameAsc()).thenReturn(List.of(s));var result=service.evaluateAll(Map.of("occupation","Farmer")).get(0);assertThat(result.status()).isEqualTo("NEED_MORE_INFORMATION");assertThat(result.checks().get(0).passed()).isNull();}
 @Test void broad_and_narrow_education_is_missing_not_rejected(){Scheme s=rule("education_level","==","Undergraduate");Mockito.when(repo.findByActiveTrueOrderByNameAsc()).thenReturn(List.of(s));var result=service.evaluateAll(Map.of("education_level","Graduate")).get(0);assertThat(result.status()).isEqualTo("NEED_MORE_INFORMATION");assertThat(result.checks().get(0).passed()).isNull();}
 private Scheme rule(String field,String operator,Object value){Scheme s=new Scheme();s.setName("Test scheme");s.setActive(true);EligibilityRule r=new EligibilityRule();r.setScheme(s);r.setField(field);r.setOperator(operator);r.setValue(value);r.setValueType("string");s.getRules().add(r);return s;}
}
