package com.bhashasetu.api;

import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;
import com.bhashasetu.dto.EligibilityDtos.*; import com.bhashasetu.model.Scheme; import com.bhashasetu.repository.SchemeRepository; import com.bhashasetu.service.*;
import com.fasterxml.jackson.databind.*; import com.fasterxml.jackson.databind.PropertyNamingStrategies; import java.util.*; import org.junit.jupiter.api.*; import org.springframework.http.MediaType; import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter; import org.springframework.test.web.servlet.MockMvc; import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

class SchemeControllerContractTest {
 private final SchemeRepository schemes=mock(SchemeRepository.class); private final EligibilityService eligibility=mock(EligibilityService.class); private final ConversationService conversation=mock(ConversationService.class); private final RedisSessionService sessions=mock(RedisSessionService.class);
 private MockMvc mvc;
 @BeforeEach void setup(){ObjectMapper mapper=new ObjectMapper().setPropertyNamingStrategy(PropertyNamingStrategies.SNAKE_CASE);mvc=MockMvcBuilders.standaloneSetup(new SchemeController(schemes,eligibility,conversation,sessions)).setMessageConverters(new MappingJackson2HttpMessageConverter(mapper)).setControllerAdvice(new ApiExceptionHandler()).build();}
 @Test void catalogue_uses_existing_scheme_json_names() throws Exception {Scheme s=new Scheme();s.setName("Scheme A");s.setActive(true);when(schemes.findByActiveTrueOrderByNameAsc()).thenReturn(List.of(s));mvc.perform(get("/api/schemes")).andExpect(status().isOk()).andExpect(jsonPath("$[0].name").value("Scheme A")).andExpect(jsonPath("$[0].is_active").value(true)).andExpect(jsonPath("$[0].manual_conditions").isArray());}
 @Test void eligibility_uses_snake_case_result_contract() throws Exception {var result=new EligibilityResult(5L,"Scheme A","ELIGIBLE",List.of(),List.of(),List.of(),null);when(eligibility.evaluateAll(anyMap())).thenReturn(List.of(result));mvc.perform(post("/api/eligibility").contentType(MediaType.APPLICATION_JSON).content("{\"attributes\":{\"age\":20}}")).andExpect(status().isOk()).andExpect(jsonPath("$[0].scheme_id").value(5)).andExpect(jsonPath("$[0].scheme_name").value("Scheme A")).andExpect(jsonPath("$[0].missing_fields").isArray());}
 @Test void conversation_accepts_and_returns_snake_case_contract() throws Exception {Map<String,Object> response=new LinkedHashMap<>();response.put("ai_text","Question");response.put("potential_schemes",List.of());response.put("next_question",Map.of("field","age"));response.put("audio_url",null);when(conversation.turn(any())).thenReturn(response);mvc.perform(post("/conversation").contentType(MediaType.APPLICATION_JSON).content("{\"text\":\"hello\",\"session_id\":\"session_1\",\"skipped_fields\":[]}")).andExpect(status().isOk()).andExpect(jsonPath("$.ai_text").value("Question")).andExpect(jsonPath("$.potential_schemes").isArray()).andExpect(jsonPath("$.next_question.field").value("age"));}
 @Test void delete_session_returns_existing_contract() throws Exception {mvc.perform(delete("/session/session_1")).andExpect(status().isOk()).andExpect(jsonPath("$.deleted").value(true));verify(sessions).delete("session_1");}
}
