package com.bhashasetu.service;
import com.bhashasetu.dto.EligibilityDtos.*; import com.bhashasetu.model.*; import com.bhashasetu.repository.SchemeRepository; import java.math.*; import java.util.*; import org.springframework.stereotype.Service;
@Service public class EligibilityService {
 private final SchemeRepository schemes; private final NormalizationService normalizer; private static final Set<String> SOFT=Set.of("occupation","employment_status","education_level");
 public EligibilityService(SchemeRepository s,NormalizationService n){schemes=s;normalizer=n;}
 public List<EligibilityResult> evaluateAll(Map<String,Object> attrs){Map<String,Object> normalized=normalizer.normalizeAttributes(attrs); return schemes.findByActiveTrueOrderByNameAsc().stream().map(s->evaluate(s,normalized)).toList();}
 public EligibilityResult evaluate(Scheme scheme,Map<String,Object> attrs){List<RuleCheck> checks=new ArrayList<>(); List<String> missing=new ArrayList<>(); boolean failed=false; for(EligibilityRule r:scheme.getRules()){String field=normalizer.alias(r.getField()); Object expected=normalizeRuleValue(field,r.getValue()); Object actual=attrs.get(field); Boolean passed=null; if(actual!=null){passed=compare(r.getOperator(),actual,expected); if(Boolean.FALSE.equals(passed)&&SOFT.contains(field))passed=null;} if(passed==null)missing.add(field); if(Boolean.FALSE.equals(passed))failed=true; checks.add(new RuleCheck(field,r.getOperator(),expected,actual,passed));} List<String>manual=new ArrayList<>(scheme.getManualConditions()==null?List.of():scheme.getManualConditions()); if(scheme.getOtherEligibilityConditions()!=null&&!scheme.getOtherEligibilityConditions().isBlank()&&!manual.contains(scheme.getOtherEligibilityConditions()))manual.add(scheme.getOtherEligibilityConditions()); String status,reason=null; if(!scheme.isActive()){status="NOT_ELIGIBLE";reason="inactive_scheme";}else if(failed){status="NOT_ELIGIBLE";reason="rule_not_matched";}else if(!missing.isEmpty()||checks.isEmpty()){status="NEED_MORE_INFORMATION";reason=checks.isEmpty()?"no_rules":"missing_information";}else if(!manual.isEmpty()){status="POTENTIALLY_ELIGIBLE";reason="manual_review_required";}else status="ELIGIBLE"; return new EligibilityResult(scheme.getId(),scheme.getName(),status,checks,missing,manual,reason);}
 private Object normalizeRuleValue(String f,Object v){if(v instanceof Collection<?> c)return c.stream().map(x->normalizer.normalize(f,x)).toList(); return normalizer.normalize(f,v);}
 private boolean compare(String op,Object actual,Object expected){String o=op.trim().toUpperCase(Locale.ROOT); if(o.equals("EQUALS"))o="=="; if(o.equals("NOT_EQUALS"))o="!="; if(o.equals("GREATER_THAN"))o=">"; if(o.equals("GREATER_THAN_OR_EQUAL"))o=">="; if(o.equals("LESS_THAN"))o="<"; if(o.equals("LESS_THAN_OR_EQUAL"))o="<="; if(o.equals("IN"))return expected instanceof Collection<?> c&&c.contains(actual); if(o.equals("NOT_IN"))return expected instanceof Collection<?> c&&!c.contains(actual); int c=((Comparable)actual).compareTo(expected); return switch(o){case "=="->c==0;case "!="->c!=0;case ">"->c>0;case ">="->c>=0;case "<"->c<0;case "<="->c<=0;default->throw new IllegalArgumentException("Unsupported operator: "+op);};}
}
