package com.bhashasetu.service;
import java.math.*; import java.util.*;
import org.springframework.stereotype.Service;
@Service public class NormalizationService {
 private static final Set<String> FIELDS=Set.of("age","annual_income","gender","state","is_disabled","state_or_ut","family_annual_income","individual_monthly_income","social_category","occupation","employment_status","student_status","education_level","farmer_status","disability_status","disability_percentage","bpl_status","rural_urban","widow_status","minority_status","marital_status");
 private static final Set<String> INTS=Set.of("age"), DECIMALS=Set.of("annual_income","family_annual_income","individual_monthly_income","disability_percentage"), BOOLS=Set.of("is_disabled","student_status","farmer_status","disability_status","bpl_status","widow_status","minority_status");
 private static final Map<String,String> ALIASES=Map.of("state","state_or_ut","is_disabled","disability_status","category","social_category","social_category","social_category");
 public Map<String,Object> normalizeAttributes(Map<String,Object> input){ Map<String,Object> out=new LinkedHashMap<>(); if(input==null)return out; for(var e:input.entrySet()){String f=alias(e.getKey()); if(!FIELDS.contains(f))throw new IllegalArgumentException("Unsupported eligibility field: "+e.getKey()); if(e.getValue()!=null && !(e.getValue() instanceof String s && s.isBlank())) out.put(f,normalize(f,e.getValue()));} return out; }
 public String alias(String field){return ALIASES.getOrDefault(field,field);}
 public Object normalize(String field,Object value){ field=alias(field); if(INTS.contains(field)){try{return new BigDecimal(value.toString().trim()).toBigIntegerExact();}catch(Exception e){throw invalid(field);}} if(DECIMALS.contains(field)){try{BigDecimal n=new BigDecimal(value.toString().trim()); if(n.signum()<0) throw invalid(field); if(field.equals("disability_percentage")&&n.compareTo(BigDecimal.valueOf(100))>0)throw invalid(field); return n.stripTrailingZeros();}catch(IllegalArgumentException e){throw e;}catch(Exception e){throw invalid(field);}} if(BOOLS.contains(field)){if(value instanceof Boolean b)return b; if("true".equalsIgnoreCase(value.toString())||"false".equalsIgnoreCase(value.toString()))return Boolean.parseBoolean(value.toString()); throw invalid(field);} String s=value.toString().trim().toLowerCase(Locale.ROOT); if(s.isEmpty())throw invalid(field); if(field.equals("state_or_ut")) return state(s); if(field.equals("social_category"))return category(s); return s; }
 private IllegalArgumentException invalid(String f){return new IllegalArgumentException("Invalid value for "+f);}
 private String state(String s){Map<String,String> a=Map.of("up","uttar pradesh","u.p.","uttar pradesh","mp","madhya pradesh","wb","west bengal","tn","tamil nadu","odisha","odisha","orissa","odisha","nct delhi","delhi");return a.getOrDefault(s,s);}
 private String category(String s){Map<String,String>a=Map.of("scheduled caste","sc","scheduled tribe","st","other backward classes","obc","other backward class","obc","unreserved","general","ur","general"); return a.getOrDefault(s,s);}
}
