package com.bhashasetu.service;
import com.bhashasetu.config.BhashaSetuProperties; import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import java.time.Duration; import java.util.*; import java.util.regex.Pattern; import org.springframework.data.redis.core.StringRedisTemplate; import org.springframework.stereotype.Service;
@Service public class RedisSessionService {
 private static final Pattern ID=Pattern.compile("[A-Za-z0-9_-]{1,128}"); private final StringRedisTemplate redis; private final ObjectMapper json; private final BhashaSetuProperties props;
 public RedisSessionService(StringRedisTemplate r,ObjectMapper j,BhashaSetuProperties p){redis=r;json=j;props=p;} private String key(String id){if(id==null||!ID.matcher(id).matches())throw new IllegalArgumentException("session_id must contain 1-128 letters, digits, underscores or hyphens.");return props.getSessionPrefix()+":"+id;}
 public State get(String id){try{String raw=redis.opsForValue().get(key(id)); if(raw==null)return new State(new LinkedHashMap<>(),0,false); redis.expire(key(id),Duration.ofSeconds(props.getSessionTtlSeconds())); return json.readValue(raw,new TypeReference<State>(){});}catch(IllegalArgumentException e){throw e;}catch(Exception e){throw new IllegalStateException("Conversation storage is unavailable. Please try again later.",e);}}
 public State merge(String id,Map<String,Object> update){State old=get(id);Map<String,Object> p=new LinkedHashMap<>(old.profile());p.putAll(update);State next=new State(p,old.attempts()+1,false);save(id,next);return next;} public void touch(String id){redis.expire(key(id),Duration.ofSeconds(props.getSessionTtlSeconds()));} public void delete(String id){redis.delete(key(id));} public void finalize(String id,State s){save(id,new State(s.profile(),s.attempts(),true));}
 private void save(String id,State s){try{redis.opsForValue().set(key(id),json.writeValueAsString(s),Duration.ofSeconds(props.getSessionTtlSeconds()));}catch(Exception e){throw new IllegalStateException("Conversation storage is unavailable. Please try again later.",e);}}
 public record State(Map<String,Object> profile,int attempts,boolean finalized){}
}
