package com.bhashasetu.api;
import com.bhashasetu.dto.EligibilityDtos.*; import com.bhashasetu.model.*; import com.bhashasetu.repository.SchemeRepository; import com.bhashasetu.service.*; import java.util.*; import org.springframework.http.*; import org.springframework.web.bind.annotation.*;
@RestController public class SchemeController {
 private final SchemeRepository schemes; private final EligibilityService eligibility; private final ConversationService conversation; private final RedisSessionService sessions;
 public SchemeController(SchemeRepository s,EligibilityService e,ConversationService c,RedisSessionService r){schemes=s;eligibility=e;conversation=c;sessions=r;}
 @GetMapping("/health") public Map<String,String> health(){return Map.of("status","ok");}
 @GetMapping("/api/schemes") public List<Map<String,Object>> list(@RequestParam(required=false) String q){return (q==null||q.isBlank()?schemes.findByActiveTrueOrderByNameAsc():schemes.searchActive(q)).stream().map(this::scheme).toList();}
 @GetMapping("/api/schemes/{id}") public Map<String,Object> detail(@PathVariable Long id){return scheme(schemes.findWithRulesById(id).orElseThrow(()->new NoSuchElementException("Scheme not found")));}
 @PostMapping("/api/eligibility") public List<EligibilityResult> eligibility(@RequestBody EligibilityRequest input){return eligibility.evaluateAll(input.attributes());}
 @PostMapping("/conversation") public Map<String,Object> conversation(@RequestBody ConversationRequest request){return conversation.turn(request);}
 @DeleteMapping("/session/{sessionId}") public Map<String,Boolean> deleteSession(@PathVariable String sessionId){sessions.delete(sessionId);return Map.of("deleted",true);}
 @PostMapping(value="/speech-to-text",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) public ResponseEntity<Map<String,String>> speechBoundary(){return ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED).body(Map.of("detail","Speech-to-text provider must be configured for the Java deployment."));}
 private Map<String,Object> scheme(Scheme s){Map<String,Object> m=new LinkedHashMap<>();m.put("id",s.getId());m.put("name",s.getName());m.put("description",s.getDescription());m.put("category",s.getCategory());m.put("state",s.getState());m.put("official_url",s.getOfficialUrl());m.put("government_level",s.getGovernmentLevel());m.put("ministry_or_department",s.getMinistryOrDepartment());m.put("status_confidence",s.getStatusConfidence());m.put("secondary_source_url",s.getSecondarySourceUrl());m.put("last_checked_date",s.getLastCheckedDate());m.put("benefit_type",s.getBenefitType());m.put("benefit_summary",s.getBenefitSummary());m.put("benefit_amount",s.getBenefitAmount());m.put("application_method",s.getApplicationMethod());m.put("official_application_url",s.getOfficialApplicationUrl());m.put("confidence_notes",s.getConfidenceNotes());m.put("other_eligibility_conditions",s.getOtherEligibilityConditions());m.put("manual_conditions",s.getManualConditions());m.put("is_active",s.isActive());m.put("rules",s.getRules().stream().map(r->Map.of("id",r.getId(),"field",r.getField(),"operator",r.getOperator(),"value",r.getValue(),"value_type",r.getValueType())).toList());return m;}
}
